import cv2
import requests
import json

# load api key
f = open("apiKey.json", 'r')
data = json.loads(f.read())
subdomain = "c026"
camera_id = "FFFFFFFF"

headers = {"content-type": "application/json", "Authentication": data["api"]}

# Step 1: login

requestContent = f'{{"username": "{data["username"]}", "password": "{data["password"]}"}}'
print(requestContent)
response0 = requests.post(url="https://login.eagleeyenetworks.com/g/aaa/authorize", json=requestContent, headers=headers);

print(response0.raw)


# request session id from api
# refresh every 15 min

#url = f"https://{subdomain}.eagleeyenetworks.com/api/v2/media/cameras/{camera_id}/streams?A={api_key}"

#response = requests.get(url)

#print(response.json())

#GET rtsp://[active_brand_subdomain].eagleeyenetworks.com:554/api/v2/media/streams/[Session ID that generated by server]/rtsp

#cap = cv2.VideoCapture(rstpUrl)

#while (cap.isOpened()):
    #ret, frame = cap.read()
    #cv2.imshow('frame', frame)
    #if cv2.waitKey(20) & 0xFF == ord('q'):
    #    break
#cap.release()
#cv2.destroyAllWindows()